const helper = {
    name: "Name",
    surname: "Surname",
    position: "Position",
    profileForm:"Profile Form",
    birthday: "Birth Date",
    email: "Email",
    phone: "Phone",
    country: "Country",
    city: "City",
    education: "Education",
    skills: "Skills",
    workExp: "Work Experience",
    projects: "Projects",
    languages: "Languages",
    certNcourse: "Certifications & courses",
    contactInfo:"Contact Info",
    eduInfo:"Education Info",
    eduLabel:"Educational Institution Name",
    departmentLabel:"Department",
    addButton:"Add",
    removeButton:"Remove",
    workeExperience:"Work Experience",
    workPlace:"Workplace",
    description:"Description",
    labelEarly:"Early",
    labelLate:"Late",
    save:"Save",
    language:"Languages",
    personalInfo:"Personal Info",
    certAndCourse:"Certifications & Courses",
    workCity:"City",
    workCountry:"Country",
    projectName:"Project Name",
    responsibilities:"Responsibilities",
    years:"Years",
    profilePicture:"Profile Picture",
    summary:"Summary"

  };

export default helper;